In [1]:
from sklearn.datasets import make_classification
X, y = make_classification(random_state=42)

In [3]:
X,y=make_classification(n_samples=10000,
                    n_features=20, 
                    n_informative=2,
                    n_redundant=2,
                    n_repeated=0,
                    weights=[0.9,0.1],
                    n_classes=2,
                    random_state=42)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
from collections import Counter
Counter(y)

Counter({np.int64(0): 8968, np.int64(1): 1032})

In [10]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=5,shuffle=True,random_state=42)
for train_index,test_index in kf.split(X,y):
   
    X_train,X_test=X[train_index],X[test_index]
    y_train,y_test=y[train_index],y[test_index]

    print(Counter(y_test))

Counter({np.int64(0): 1776, np.int64(1): 224})
Counter({np.int64(0): 1788, np.int64(1): 212})
Counter({np.int64(0): 1800, np.int64(1): 200})
Counter({np.int64(0): 1810, np.int64(1): 190})
Counter({np.int64(0): 1794, np.int64(1): 206})


In [11]:
from sklearn.model_selection import StratifiedKFold
stf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
for train_index,test_index in stf.split(X,y):

    X_train,X_test=X[train_index],X[test_index]
    y_train,y_test=y[train_index],y[test_index]

    print(Counter(y_test))

Counter({np.int64(0): 1794, np.int64(1): 206})
Counter({np.int64(0): 1794, np.int64(1): 206})
Counter({np.int64(0): 1794, np.int64(1): 206})
Counter({np.int64(0): 1793, np.int64(1): 207})
Counter({np.int64(0): 1793, np.int64(1): 207})


### cross validation  on logistic_regression

In [24]:
from sklearn.linear_model import LogisticRegression

In [22]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), X, y, cv=kf,scoring="accuracy")

array([0.936 , 0.9365, 0.9295, 0.9395, 0.9405])

### cross validation on Decision_tree

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
cross_val_score(DecisionTreeClassifier(), X, y, cv=kf,scoring="accuracy")

array([0.928 , 0.923 , 0.9295, 0.925 , 0.9315])

### cross validation on Random_forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(), X, y, cv=kf,scoring="accuracy")

array([0.9525, 0.942 , 0.9435, 0.942 , 0.9525])

### cross validation with cv as int parameter

In [28]:
cross_val_score(RandomForestClassifier(), X, y, cv=5,scoring="accuracy")

array([0.9525, 0.949 , 0.939 , 0.954 , 0.941 ])